# Generated by Django 3.1.4 on 2020-12-29 02:07

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('body_type', models.CharField(max_length=30)),
                ('engine', models.CharField(max_length=30)),
                ('fuel_type', models.CharField(max_length=10)),
                ('transmission', models.CharField(max_length=10)),
                ('drive', models.CharField(max_length=10)),
                ('brakes', models.CharField(max_length=10)),
                ('car_image', models.ImageField(upload_to='static/images')),
                ('car_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('credit_card_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_period', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('purpose_acquisition', models.CharField(max_length=50)),
                ('payment_method_info', models.CharField(max_length=50)),
                ('date_created', models.DateField()),
                ('date_closed', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.car')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.client')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=20)),
                ('date_created', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TechInspectionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.contract')),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.manager')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.request')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_text', models.CharField(max_length=200)),
                ('date_receipt', models.DateField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.client')),
            ],
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.user')),
            ],
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.user'),
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_damage_description', models.TextField()),
                ('phys_damage_description', models.TextField()),
                ('date_inspection', models.DateField()),
                ('date_created_report', models.DateField()),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.contract')),
                ('mechanic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.mechanic')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.manager'),
        ),
        migrations.CreateModel(
            name='CloseRentalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.contract')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.request')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.user'),
        ),
        migrations.CreateModel(
            name='CarRentalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose_acquisition', models.CharField(max_length=50)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.client')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.request')),
            ],
        ),
    ]
