# Generated by Django 3.1.4 on 2020-12-29 02:12

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrentalrequest',
            name='rental_period',
            field=django.contrib.postgres.fields.ranges.DateRangeField(default=['2020-12-25', '2020-12-29']),
            preserve_default=False,
        ),
    ]
